### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by xccyue** [L-Scofano/STAG#1]
Hi,

There is an error when I train the code following the command.

I can train the stage 1 and 2 successfully. But it occurs "RuntimeError: Error(s) in loading state_dict for GCN_POSE: size mismatch for g_w1.0.weight: copying a param with shape torch.Size([128, 308]) from checkpoint, the shape in current model is torch.Size([128, 436])." when I train the stage 3. The error comes from line 276 "model_dict.update(traj_dict)".

I found that in the model GCN_TRAJ, the input of g_w1 is root_his_dct,hcont, but in the model GRU_POSE, the input of g_w1 is root_his_dct, hx_root, hcont. They are different dimensions but with the same name. 

Thanks for your time! Looking forward to the reply.

**Comment by L-Scofano** [comment]
Hello,

Thanks for checking out our project! Apologies for any confusion; it appears that you may have trained the third stage using an outdated version of the configuration file. I've recently updated the code. The issue was related to the use of `GRU_POSE`, which should not be employed. Instead, please utilize `GCN_TPOSE` within `/models/gcn.py`.

Give that a try, and let me know if it sorts out your issue. Feel free to reach out if you have any questions!

Best regards.

**Comment by xccyue** [comment]
Thank you!
